/*******************************************************************************
*  This file is part of the MapShot plugin
*  Copyright (C) 2009 Roman Tsisyk <roman@tsisyk.com>
*
*  This library is free software; you can redistribute it and/or
*  modify it under the terms of the GNU Lesser General Public
*  License as published by the Free Software Foundation; either
*  version 2.1 of the License, or (at your option) any later version.
*
*  This library is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
*  Lesser General Public License for more details.
*
*  You should have received a copy of the GNU Lesser General Public
*  License along with this library; if not, write to the Free Software
*  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
*******************************************************************************/

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(49574EF8-F6E0-4172-AAD7-1C94E8DAD4ED),
	version(1.0),
	helpstring("MapShotPlugin 1.0 Type Library")
]

library MapShotPluginLib
{
	importlib("stdole2.tlb");
};
